/* config_hw.h — generated by sweep.py — DO NOT EDIT MANUALLY
 *
 * PV_N_PARALLEL : modules wired in parallel  → scales I_MPP
 * PV_N_SERIES   : modules wired in series    → scales V_MPP
 * BAT_N_PARALLEL: batteries in parallel      → scales c_nom
 */
#ifndef CONFIG_HW_H
#define CONFIG_HW_H

#define PV_N_PARALLEL  1
#define PV_N_SERIES    2

#define BAT_N_PARALLEL 2

#endif /* CONFIG_HW_H */
